name: Deploy project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1st job
      - name: Get code
        uses: actions/checkout@v4
      # 2nd job
      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # 3rd job
      - name: Install dependencies
        run: npm ci
      # 4th job
      - name: Run tests
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # 1st job
      - name: Get code
        uses: actions/checkout@v4
      # 2nd job
      - name: Install nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      # 3rd job
      - name: Install dependencies
        run: npm ci
      # 4th job
      - name: Build code
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
